"""added proposed nodes

Revision ID: 33df5f6ae6ec
Revises: bfd584b09546
Create Date: 2026-02-22 23:15:30.218591

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '33df5f6ae6ec'
down_revision = 'bfd584b09546'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proposed_nodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('node_type', postgresql.ENUM('global_goal', 'theorem', 'lemma', 'corollary', 'definition', 'numerical_eval', name='node_type_enum', create_type=False), nullable=False),
    sa.Column('branch_name', sa.Text(), nullable=False),
    sa.Column('lean_file_path', sa.Text(), nullable=False),
    sa.Column('latex_file_path', sa.Text(), nullable=True),
    sa.Column('proposed_parent_title', sa.Text(), nullable=True),
    sa.Column('proposed_parent_id', sa.UUID(), nullable=True),
    sa.Column('proposed_dependencies', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', postgresql.ENUM('draft', 'verifying', 'valid', 'valid_with_sorry', 'invalid', 'merged', 'rejected', name='proposal_status_enum'), nullable=False),
    sa.Column('is_exposed', sa.Boolean(), nullable=True),
    sa.Column('verification_log', sa.Text(), nullable=True),
    sa.Column('merged_graph_node_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['merged_graph_node_id'], ['graph_index.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proposed_parent_id'], ['graph_index.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'title', name='uniq_project_pnode_title')
    )
    with op.batch_alter_table('proposed_nodes', schema=None) as batch_op:
        batch_op.create_index('ix_status_exposed', ['status', 'is_exposed'], unique=False)

    with op.batch_alter_table('graph_index', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_graph_index_file_path'))
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('graph_index', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', postgresql.ENUM('pending', 'in_review', 'verified', 'error', name='node_status_enum'), autoincrement=False, nullable=False))
        batch_op.create_index(batch_op.f('ix_graph_index_file_path'), ['file_path'], unique=False)

    with op.batch_alter_table('proposed_nodes', schema=None) as batch_op:
        batch_op.drop_index('ix_status_exposed')

    op.drop_table('proposed_nodes')
    # ### end Alembic commands ###
