"""Phase 1: Statement centric schema

Revision ID: 46c7ac45000f
Revises: 33df5f6ae6ec
Create Date: 2026-02-23 23:37:06.854852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46c7ac45000f'
down_revision = '33df5f6ae6ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('graph_index', schema=None) as batch_op:
        batch_op.add_column(sa.Column('statement_id', sa.UUID(), nullable=False))
        batch_op.add_column(sa.Column('parent_statement_id', sa.UUID(), nullable=True))
        batch_op.add_column(sa.Column('proven_by_statement_id', sa.UUID(), nullable=True))
        batch_op.add_column(sa.Column('is_resolved', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('lean_relative_path', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('latex_relative_path', sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f('ix_graph_index_statement_id'), ['statement_id'], unique=False)
        batch_op.create_unique_constraint('uniq_project_statement_id', ['project_id', 'statement_id'])
        batch_op.drop_column('latex_file_path')
        batch_op.drop_column('commit_hash')
        batch_op.drop_column('file_path')
        batch_op.drop_column('start_line')
        batch_op.drop_column('end_line')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('main_commit_sha', sa.String(length=40), nullable=True))

    with op.batch_alter_table('proposed_nodes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_statement_id', sa.UUID(), nullable=False))
        batch_op.add_column(sa.Column('fork_repo_full_name', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('github_pr_number', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('commit_sha', sa.String(length=40), nullable=True))
        batch_op.drop_index(batch_op.f('ix_status_exposed'))
        batch_op.drop_constraint(batch_op.f('uniq_project_pnode_title'), type_='unique')
        batch_op.create_index(batch_op.f('ix_proposed_nodes_parent_statement_id'), ['parent_statement_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('proposed_nodes_proposed_parent_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('proposed_nodes_merged_graph_node_id_fkey'), type_='foreignkey')
        batch_op.drop_column('proposed_parent_title')
        batch_op.drop_column('merged_graph_node_id')
        batch_op.drop_column('proposed_parent_id')
        batch_op.drop_column('is_exposed')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proposed_nodes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_exposed', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('proposed_parent_id', sa.UUID(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('merged_graph_node_id', sa.UUID(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('proposed_parent_title', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('proposed_nodes_merged_graph_node_id_fkey'), 'graph_index', ['merged_graph_node_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('proposed_nodes_proposed_parent_id_fkey'), 'graph_index', ['proposed_parent_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_proposed_nodes_parent_statement_id'))
        batch_op.create_unique_constraint(batch_op.f('uniq_project_pnode_title'), ['project_id', 'title'], postgresql_nulls_not_distinct=False)
        batch_op.create_index(batch_op.f('ix_status_exposed'), ['status', 'is_exposed'], unique=False)
        batch_op.drop_column('commit_sha')
        batch_op.drop_column('github_pr_number')
        batch_op.drop_column('fork_repo_full_name')
        batch_op.drop_column('parent_statement_id')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('main_commit_sha')

    with op.batch_alter_table('graph_index', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_line', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('start_line', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('file_path', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('commit_hash', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('latex_file_path', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_constraint('uniq_project_statement_id', type_='unique')
        batch_op.drop_index(batch_op.f('ix_graph_index_statement_id'))
        batch_op.drop_column('latex_relative_path')
        batch_op.drop_column('lean_relative_path')
        batch_op.drop_column('is_resolved')
        batch_op.drop_column('proven_by_statement_id')
        batch_op.drop_column('parent_statement_id')
        batch_op.drop_column('statement_id')

    # ### end Alembic commands ###
