"""Add graph hierarchy and latex path

Revision ID: bfd584b09546
Revises: 925677d2e4e4
Create Date: 2026-02-20 06:37:35.625715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfd584b09546'
down_revision = '925677d2e4e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('graph_index', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latex_file_path', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('parent_id', sa.UUID(), nullable=True))
        batch_op.create_foreign_key(None, 'graph_index', ['parent_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('graph_index', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('parent_id')
        batch_op.drop_column('latex_file_path')

    # ### end Alembic commands ###
